name: Swift

on: [push, pull_request, workflow_dispatch]

jobs:
#   test_macOS:

#     runs-on: macos-latest

#     steps:
#     - uses: actions/checkout@v2
#     - name: Build
#       run: swift build
#     - name: Run tests
#       run: swift test
      
#   test_linux:
#     strategy:
#       matrix:
#         image: ["swift:5.0", "swift:5.1", "swift:5.2", "swift:5.3", "swift:5.4"]
        
#     runs-on: ubuntu-latest
#     container: ${{ matrix.image }}
    
#     steps:
#     - uses: actions/checkout@v2
#     - name: Build
#       run: swift build
#     - name: Run tests
#       run: swift test

  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        swift: ["5.0", "5.1", "5.2", "5.3", "5.4"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: fwal/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift }}
      - uses: actions/checkout@v2
      - name: Build
        run: swift build --build-tests
      - name: Run tests
        run: swift test

  
